name: toutine
description: Toutine Flutter Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  feature_home:
    path: ./feature/home

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true
