name: domain
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  data:
    path: ../data

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
